api_version = "2025-01"

[[input.handlers]]
name = "run"
type = "function"
entrypoint = "src/run.js"

[[extensions]]
name = "t:name"
description = "t:description"
handle = "apply-discount-rules"
type = "ui_extension"
uid = "e6ee1a42-8de6-447d-23ea-4679c1178581d6329f32"

[[extensions.targeting]]
module = "./src/DiscountFunctionSettings.js"
target = "admin.discount-details.function-settings.render"
